insert into Country values (1,'Afghanistan');
insert into Country values (2,'Albania');
insert into Country values (3,'Algeria');
insert into Country values (4,'Andorra');
insert into Country values (5,'Angola');
insert into Country values (6,'Antigua & Deps');
insert into Country values (7,'Argentina');
insert into Country values (8,'Armenia');
insert into Country values (9,'Australia');
insert into Country values (10,'Austria');
insert into Country values (11,'Azerbaijan');
insert into Country values (12,'Bahamas');
insert into Country values (13,'Bahrain');
insert into Country values (14,'Bangladesh');
insert into Country values (15,'Barbados');
insert into Country values (16,'Belarus');
insert into Country values (17,'Belgium');
insert into Country values (18,'Belize');
insert into Country values (19,'Benin');
insert into Country values (20,'Bhutan');
insert into Country values (21,'Bolivia');
insert into Country values (22,'Bosnia Herzegovina');
insert into Country values (23,'Botswana');
insert into Country values (24,'Brazil');
insert into Country values (25,'Brunei');
insert into Country values (26,'Bulgaria');
insert into Country values (27,'Burkina');
insert into Country values (28,'Burundi');
insert into Country values (29,'Cambodia');
insert into Country values (30,'Cameroon');
insert into Country values (31,'Canada');
insert into Country values (32,'Cape Verde');
insert into Country values (33,'Central African Rep');
insert into Country values (34,'Chad');
insert into Country values (35,'Chile');
insert into Country values (36,'China');
insert into Country values (37,'Colombia');
insert into Country values (38,'Comoros');
insert into Country values (39,'Congo');
insert into Country values (40,'Congo {Democratic Rep}');
insert into Country values (41,'Costa Rica');
insert into Country values (42,'Croatia');
insert into Country values (43,'Cuba');
insert into Country values (44,'Cyprus');
insert into Country values (45,'Czech Republic');
insert into Country values (46,'Denmark');
insert into Country values (47,'Djibouti');
insert into Country values (48,'Dominica');
insert into Country values (49,'Dominican Republic');
insert into Country values (50,'East Timor');
insert into Country values (51,'Ecuador');
insert into Country values (52,'Egypt');
insert into Country values (53,'El Salvador');
insert into Country values (54,'Equatorial Guinea');
insert into Country values (55,'Eritrea');
insert into Country values (56,'Estonia');
insert into Country values (57,'Ethiopia');
insert into Country values (58,'Fiji');
insert into Country values (59,'Finland');
insert into Country values (60,'France');
insert into Country values (61,'Gabon');
insert into Country values (62,'Gambia');
insert into Country values (63,'Georgia');
insert into Country values (64,'Germany');
insert into Country values (65,'Ghana');
insert into Country values (66,'Greece');
insert into Country values (67,'Grenada');
insert into Country values (68,'Guatemala');
insert into Country values (69,'Guinea');
insert into Country values (70,'Guinea-Bissau');
insert into Country values (71,'Guyana');
insert into Country values (72,'Haiti');
insert into Country values (73,'Honduras');
insert into Country values (74,'Hungary');
insert into Country values (75,'Iceland');
insert into Country values (76,'India');
insert into Country values (77,'Indonesia');
insert into Country values (78,'Iran');
insert into Country values (79,'Iraq');
insert into Country values (80,'Ireland {Republic}');
insert into Country values (81,'Israel');
insert into Country values (82,'Italy');
insert into Country values (83,'Ivory Coast');
insert into Country values (84,'Jamaica');
insert into Country values (85,'Japan');
insert into Country values (86,'Jordan');
insert into Country values (87,'Kazakhstan');
insert into Country values (88,'Kenya');
insert into Country values (89,'Kiribati');
insert into Country values (90,'Korea North');
insert into Country values (91,'Korea South');
insert into Country values (92,'Kosovo');
insert into Country values (93,'Kuwait');
insert into Country values (94,'Kyrgyzstan');
insert into Country values (95,'Laos');
insert into Country values (96,'Latvia');
insert into Country values (97,'Lebanon');
insert into Country values (98,'Lesotho');
insert into Country values (99,'Liberia');
insert into Country values (100,'Libya');
insert into Country values (101,'Liechtenstein');
insert into Country values (102,'Lithuania');
insert into Country values (103,'Luxembourg');
insert into Country values (104,'Macedonia');
insert into Country values (105,'Madagascar');
insert into Country values (106,'Malawi');
insert into Country values (107,'Malaysia');
insert into Country values (108,'Maldives');
insert into Country values (109,'Mali');
insert into Country values (110,'Malta');
insert into Country values (111,'Marshall Islands');
insert into Country values (112,'Mauritania');
insert into Country values (113,'Mauritius');
insert into Country values (114,'Mexico');
insert into Country values (115,'Micronesia');
insert into Country values (116,'Moldova');
insert into Country values (117,'Monaco');
insert into Country values (118,'Mongolia');
insert into Country values (119,'Montenegro');
insert into Country values (120,'Morocco');
insert into Country values (121,'Mozambique');
insert into Country values (122,'Myanmar, {Burma}');
insert into Country values (123,'Namibia');
insert into Country values (124,'Nauru');
insert into Country values (125,'Nepal');
insert into Country values (126,'Netherlands');
insert into Country values (127,'New Zealand');
insert into Country values (128,'Nicaragua');
insert into Country values (129,'Niger');
insert into Country values (130,'Nigeria');
insert into Country values (131,'Norway');
insert into Country values (132,'Oman');
insert into Country values (133,'Pakistan');
insert into Country values (134,'Palau');
insert into Country values (135,'Panama');
insert into Country values (136,'Papua New Guinea');
insert into Country values (137,'Paraguay');
insert into Country values (138,'Peru');
insert into Country values (139,'Philippines');
insert into Country values (140,'Poland');
insert into Country values (141,'Portugal');
insert into Country values (142,'Qatar');
insert into Country values (143,'Romania');
insert into Country values (144,'Russian Federation');
insert into Country values (145,'Rwanda');
insert into Country values (146,'St Kitts & Nevis');
insert into Country values (147,'St Lucia');
insert into Country values (148,'Saint Vincent & the Grenadines');
insert into Country values (149,'Samoa');
insert into Country values (150,'San Marino');
insert into Country values (151,'Sao Tome & Principe');
insert into Country values (152,'Saudi Arabia');
insert into Country values (153,'Senegal');
insert into Country values (154,'Serbia');
insert into Country values (155,'Seychelles');
insert into Country values (156,'Sierra Leone');
insert into Country values (157,'Singapore');
insert into Country values (158,'Slovakia');
insert into Country values (159,'Slovenia');
insert into Country values (160,'Solomon Islands');
insert into Country values (161,'Somalia');
insert into Country values (162,'South Africa');
insert into Country values (163,'South Sudan');
insert into Country values (164,'Spain');
insert into Country values (165,'Sri Lanka');
insert into Country values (166,'Sudan');
insert into Country values (167,'Suriname');
insert into Country values (168,'Swaziland');
insert into Country values (169,'Sweden');
insert into Country values (170,'Switzerland');
insert into Country values (171,'Syria');
insert into Country values (172,'Taiwan');
insert into Country values (173,'Tajikistan');
insert into Country values (174,'Tanzania');
insert into Country values (175,'Thailand');
insert into Country values (176,'Togo');
insert into Country values (177,'Tonga');
insert into Country values (178,'Trinidad & Tobago');
insert into Country values (179,'Tunisia');
insert into Country values (180,'Turkey');
insert into Country values (181,'Turkmenistan');
insert into Country values (182,'Tuvalu');
insert into Country values (183,'Uganda');
insert into Country values (184,'Ukraine');
insert into Country values (185,'United Arab Emirates');
insert into Country values (186,'United Kingdom');
insert into Country values (187,'United States');
insert into Country values (188,'Uruguay');
insert into Country values (189,'Uzbekistan');
insert into Country values (190,'Vanuatu');
insert into Country values (191,'Vatican City');
insert into Country values (192,'Venezuela');
insert into Country values (193,'Vietnam');
insert into Country values (194,'Yemen');
insert into Country values (195,'Zambia');
insert into Country values (196,'Zimbabwe');

insert into Sport (id, name, imageName, description) values (1,'3x3 Basketball','bk3', 'Considered to be the number one urban sport in the world, 3X3 basketball has its roots in street basketball—a creative variation of the indoor game with a less formal structure. Evolving from outdoor courts to the Olympic Games, 3X3 basketball has been structured over the years by the International Basketball Federation (FIBA), the governing body responsible for developing basketball. The introduction of events such as the 3X3 World Tour and the 3X3 Superleague in France reflects the soaring popularity of this young urban sport, played in an electric atmosphere whipped up by a DJ and their music.');
insert into Sport (id, name, imageName, description) values (2,'Archery','arc', 'Archery is one of the oldest sports still practised today, and is closely linked to the development of human civilisation. Historically, archery has been used for hunting and warfare; the earliest evidence of its use comes from South African sites such as Sibudu Cave, where arrowheads dating from approximately 64,000 years ago have been found. The first recorded archery tournaments took place in the People\'s Republic of China during the Zhou dynasty (1027‑256 BC). In 1931, the sport evolved around the globe and the international archery federation—now known as World Archery—was founded.');
insert into Sport (id, name, imageName, description) values (3,'Artistic Gymnastics','gar', 'Founded in 1881, the International Gymnastics Federation is the oldest international sports federation in the world. The origin of gymnastics dates to antiquity, when it was recommended by philosophers as a way of combining physical exercise with intellectual activity. The sport grew in popularity during the 19th century as an increasing number of competitions were formed, including the gymnastics competition at the newly revived Olympic Games in Athens in 1896.');
insert into Sport (id, name, imageName, description) values (4,'Artistic Swimming','swa', 'The sport of artistic swimming developed by combining water acrobatics with music. Although the first contests were organised for men, artistic swimming later became more associated with women. After a number of demonstrations in the US in the early 20th century, the discipline grew in popularity and the first competitions were organised.');
insert into Sport (id, name, imageName, description) values (5,'Athletics','ath', 'Contested at the very first ancient Olympic Games, athletics is one of the oldest sports on record, with the names of champions documented from as far back as 776 BC. The ancient Olympic Games included events like the pentathlon, which consisted of a running race, long jump, discus throw, javelin throw, and wrestling. The first meets in modern times that can be likened to the athletics competitions we know today took place in 1840 in Shropshire, England. Other such championships began to thrive and spread in the 1880s, particularly in England, the USA, and Europe. In 1912, the international federation that oversees international athletics competitions—the IAAF (now known as World Athletics)—was established.');
insert into Sport (id, name, imageName, description) values (6,'Badmintion','bdm', 'Badminton is a racket sport whose exact origins are still a tantalising mystery. It evolved from the older games of battledore and shuttlecock, which were popular pastimes in Europe—particularly among the more affluent classes. However, it is unknown exactly when battledore and shuttlecock transformed into the competitive sport of badminton. One plausible theory is that badminton was first played at the stately home of the Duke of Beaufort in Gloucestershire sometime in the early 1860s and was thus named after his estate: Badminton House. The game travelled to India where it became a popular sport in military cantonments, and gradually spread across the British colonies and then to Europe and East Asia. Today, badminton is a global sport with widespread appeal among people of all ages and abilities.');
insert into Sport (id, name, imageName, description) values (7,'Basketball','bkb', 'Basketball was invented by James W. Naismith to keep his students fit during the winter. In December 1891, the physical education teacher at the YMCA International Training School in Springfield, USA sought a suitable indoor sport for his students, and plenty of the rules for the game he created still apply today. The first international games were played in the 1920s, and the first world championships took place in the 1950s.');
insert into Sport (id, name, imageName, description) values (8,'Beach Volleyball','vbv', 'A variation of volleyball played on sand first appeared on the beaches of Santa Monica, California in the 1920s. The first beach volleyball tournament took place in 1947 and the first circuit was launched in the 1950s, involving hundreds of players on Californian beaches. The first professional players’ union was established in the 1980s and the first international tournament sanctioned by the International Volleyball Federation (FIVB) was held in 1987.');
insert into Sport (id, name, imageName, description) values (9,'Boxing','box', 'The exact origins of the sport of boxing are unknown, though some of the earliest evidence (dating from the 3rd millennium BCE) comes from Sumerian artifacts found in present-day Iraq. Boxing was introduced to the ancient Olympic Games in 688 BC, where boxers used soft leather thongs to bind their hands and forearms for protection. Boxing seemed to disappear with the fall of the Roman Empire before resurfacing in the 17th century in England, where records of amateur boxing began in 1880. Initially, five weight categories were contested: bantam, not exceeding 54 kilos; feather, not exceeding 57 kilos; light, not exceeding 63.5 kilos; middle, not exceeding 73 kilos; and heavy, any weight.');
insert into Sport (id, name, imageName, description) values (10,'Breaking','bkg', 'Breaking is an urban dance style that originated in the United States in the 1970s. With roots in hip-hop culture, breaking first took form in the lively block parties in the Bronx borough of New York, and is characterised by acrobatic movements, stylised footwork, and the key role played by the DJ and the MC (master of ceremonies) during battles. International competitions were first held in the 1990s, popularising the dance form both among hip-hop communities and the general public along the way.');
insert into Sport (id, name, imageName, description) values (11,'Canoe Slalom','csl', 'For centuries, canoes were used as a means of transport (as well as a useful tool for hunting and fishing) in North America, Siberia, and Greenland. The sport of canoe slalom was modelled from ski slalom and began in Switzerland in 1932. The first contests were performed on flat water, but were later switched to whitewater rapids.');
insert into Sport (id, name, imageName, description) values (12,'Canoe Sprint','csp', 'For centuries, canoes were used as a means of transport (as well as a useful tool for hunting and fishing) in North America, Siberia, and Greenland. The first recorded competitive canoe sprint race took place at the British Royal Canoe Club in 1869.');
insert into Sport (id, name, imageName, description) values (13,'Cycling BMX Freestyle','bmf', 'Bicycle Motocross (BMX) Freestyle was born out of the imagination of children and teenagers in California in the 1970s, who were inspired by the moves of BMX racers in the region. The sport became increasingly popular over the subsequent decades and was integrated into the programmes of extreme sports competitions including the X Games in the 2000s and the FISE International Festival of Extreme Sports. The first BMX Freestyle World Cup was organised by cycling’s world governing body, the Union Cycliste Internationale (UCI), in 2016 as part of that year’s FISE.');
insert into Sport (id, name, imageName, description) values (14,'Cycling BMX Racing','bmx', 'BMX racing emerged from the motocross craze that took off in California in the 1960s, as youngsters began racing their bikes on improvised tracks all over the state. BMX began to develop into a proper sport in the early 1980s; in 1981 the International BMX Federation was founded, with the first BMX world championships following one year later. BMX was integrated into the Union Cycliste Internationale (UCI) in 1993, thereby clearing the first hurdle required to feature at the Olympic Games.');
insert into Sport (id, name, imageName, description) values (15,'Cycling Mountain Bike','mtb', 'Mountain bike is a relatively new sport that emerged in the 1970s, when cyclists in California decided to take their bikes off-road and explore new trails. In the 1990s, the first mountain bikes that could withstand the impact of rougher terrain were created, and the hobby subsequently took off, quickly becoming a sport in its own right. The first informal competitions took place in the late 1970s before the first official world championships were held in the 1990s.');
insert into Sport (id, name, imageName, description) values (16,'Cycling Road','crd', 'Cycling is composed of various disciplines, reflecting its age-old past and modern outlook. Road cycling is the earliest form of the sport. During the 19th century, cycling enjoyed a surge in popularity thanks to the invention of the chain-and-gearing system. The first races were organised a few years later, with the first documented event held in 1868 in Parc de Saint Cloud in Paris. Shortly thereafter, national cycling federations began to be established and an international federation, known as the Union Cycliste Internationale, was set up in 1900 to oversee the organisation of the various disciplines.');
insert into Sport (id, name, imageName, description) values (17,'Cycling Track','ctr', 'The first bicycles were invented in the 1850s and looked quite different to the bikes we know today. But it wasn’t until the 1870s that the first competitions for cycling indoors on wooden tracks were staged, with the first six‑day race taking place in London in 1878. Track cycling quickly grew in popularity and continued to develop with the creation of the International Cycling Association in 1892 and the organisation of the first world championships in Chicago in 1893.');
insert into Sport (id, name, imageName, description) values (18,'Diving','div', 'In the early 19th century, gymnasts in Germany and Sweden popularised ‘fancy’ diving by performing elaborate acrobatics while jumping into the water. Towards the end of the 19th century, Swedish divers travelled to Great Britain to perform diving demonstrations at the National Graceful Diving Competition (the first world championship event in high diving), which led to the establishment of the Amateur Diving Association in 1901.');
insert into Sport (id, name, imageName, description) values (19,'Equestrian','equ', 'Equestrian events originated in Ancient Greece, where it was thought that a perfect partnership was needed if rider and horse were to survive in battle. Dressage was therefore developed as a way of training horses for war. Equestrian events appeared at the ancient Olympic Games as chariot racing, which was a daring and exciting spectacle. The art of riding then fell into oblivion until its revival during the Renaissance. Dressage reached its peak with the creation of the world-famous Spanish Riding School in Vienna in 1729, which established the foundations of the modern discipline.');
insert into Sport (id, name, imageName, description) values (20,'Fencing','fen', 'Fencing’s origins can be found in swordplay, which has been practised for thousands of years—as evidenced by the discovery of carvings depicting fencers that date to around 1190 BCE which were discovered in a temple near Luxor, Egypt. Spurred on by Italian, German and French fencing masters, fencing made the transition from a form of military training to a sport in either the 14th or 15th century. Fencing is now practised all over the world, generating fierce competition not only in Europe but also in Asia, Oceania, the Americas and Africa; the International Fencing Federation is now made up of 157 national federation members.');
insert into Sport (id, name, imageName, description) values (21,'Football','fbl', 'Although football can trace its roots back to Ancient China, the modern version of the game was born on the streets of medieval England, before going on to become the most popular sport in the world. The (very) early games of football in medieval England involved a large mass of people who would attempt to drag a pig’s bladder—by any means possible—to markers at opposing ends of a town. Such events were well known for being as violent as they were popular. In the 16th century, English schools established the modern football codes, thereby transforming what were mob riots into a proper sport.');
insert into Sport (id, name, imageName, description) values (22,'Golf','glf', 'Golf was one of the first modern sports to codify its rules in 1754 in the town of St. Andrews in Scotland. However, the origins of this sport date back even further, as there are traces of a similar sport played in the Netherlands that arrived in the British Isles in the 15th century. At the end of the 19th century, the first women’s tournaments were established. Today, there are more than 60 million golfers and over 30,000 golf courses worldwide.');
insert into Sport (id, name, imageName, description) values (23,'Handball','hbl', 'Handball was first played towards the end of the 19th century in Scandinavia and Germany, where field handball was also gaining recognition as a sport. G.Wallström introduced the sport to Sweden in 1910. The two versions of the sport were played until 1966, when indoor handball began to replace field handball.');
insert into Sport (id, name, imageName, description) values (24,'Hockey','hoc', 'Hockey takes its name from the French word “hocquet”, meaning a shepherd’s crook in reference to the curved shape of a hockey stick. The roots of the game stretch back to antiquity, as records show an early form of the sport practised 4,000 years ago in Egypt, with variations played in what is now Ethiopia (1000 BC) and Iran (2000 BC).');
insert into Sport (id, name, imageName, description) values (25,'Judo','jud', 'Judo is a traditional Japanese martial art derived from jiu-jitsu, the hand-to-hand combat technique of ancient samurai warriors. Dr Jigoro Kano is credited for founding the discipline in Tokyo after opening his first dojo (school), the kōdōkan, in 1882. In Japanese, the word “judo” means “the gentle way,” but the traditional wrestling sport can hardly be described as such—it requires considerable physical effort. Dr. Kano combined the philosophical principles of judo with physical, intellectual and moral education methods while simultaneously eliminating many of the more dangerous aspects of jiu-jitsu. Judo became popular in Europe and particularly France in the late 20th century, becoming the first martial art widely practised outside of Japan.');
insert into Sport (id, name, imageName, description) values (26,'Marathon Swimming','ows', 'At the first three editions of the modern Olympic Games, all swimming events took place in a natural body of water prior to the inclusion of pools at the Games in 1908. Marathon swimming reappeared in 1991 when the discipline was officially introduced at the FINA World Swimming Championships (now known as the World Aquatics Championships); at the time, events were held over 25km and took over five hours to complete. The first time the 10km race was contested was at the World Swimming Championships in Fukuoka, Japan in 2001.');
insert into Sport (id, name, imageName, description) values (27,'Modern Pentathlon','mpn', 'The modern pentathlon is the successor to the ancient pentathlon, which comprised running, jumping, javelin, discus and wrestling. Baron Pierre de Coubertin, founder of the modern Olympic Games, highly appreciated the pentathlon of the ancient Games. He proposed a similar competition that would test the strengths of a “complete” athlete, but involve more modern disciplines. The growing popularity of this sport resulted in the foundation of an international federation, the Union Internationale de Pentathlon Moderne (UIPM), in 1848. It currently has over 120 member nations.');
insert into Sport (id, name, imageName, description) values (28,'Rhythmic Gymnastics','gry', 'Gymnastics is one of the oldest sports that is still practiced today with origins that date back to ancient civilisation. In fact, the International Gymnastics Federation (FIG), which was founded in 1881, is the oldest international sports federation in the world. Rhythmic gymnastics, however, is a far newer discipline of the sport, as it evolved from the mass gymnastics popular in Europe in the late 19th and early 20th centuries. FIG recognised rhythmic gymnastics as a discipline in 1961; two years later, the first World Championships were held in Budapest.');
insert into Sport (id, name, imageName, description) values (29,'Rowing','row', 'Rowing originally served as a means of transport in ancient Egypt, Greece and Rome, but it was only in England between the end of the 17th and the start of the 18th centuries that it became a sport. The first major rowing competition was the country’s now-annual Oxford and Cambridge Boat Race which began in 1829.');
insert into Sport (id, name, imageName, description) values (30,'Rugby Sevens','ru7', 'The sport of rugby can trace its origins back to medieval times in several European countries, but it was between 1845 and 1848 that the modern rugby codes were established by pupils from a school in the English town of Rugby and the University of Cambridge. In 1871, the first national federation was formed; two years later, the discipline of rugby sevens was conceived by two butchers, Ned Haig and David Sanderson, as a fund-raising event in Melrose, Scotland. In 1886, the International Rugby Board (now known as World Rugby) was established.');
insert into Sport (id, name, imageName, description) values (31,'Sailing','sal', 'International sailing races began in 1851 when members of the New York Yacht Club decided to take part in a competition in England. To compete, they built a 101‑foot schooner named America, sailed to England and won a trophy called the Hundred Guineas Cup. The trophy was then renamed The America’s Cup in memory of this first international sailing competition.');
insert into Sport (id, name, imageName, description) values (32,'Shooting','sho', 'Shooting has been an Olympic sport since the first modern Games and has been practised in Europe for hundreds of years. Some German clubs date back more than five hundred years. Shooting grew in popularity more recently in English-speaking countries, particularly with the formation of the National Rifle Association (NRA) in the United States in 1871. Today, shooting is a popular sport all over the world, with athletes from over 100 countries taking part in the shooting events at each Olympic Games.');
insert into Sport (id, name, imageName, description) values (33,'Skateboarding','skb', 'Skateboarding is a young and spectacular sport that developed in the US in the 1950s as surf culture was taking off. It was then part of the underground, alternative culture of the 1980s, going hand in hand with the values of freedom, rebellion and thrill-seeking. The sport continued to develop and became more widely accessible at the start of the 21st century, proving a huge hit among younger audiences.');
insert into Sport (id, name, imageName, description) values (34,'Sport Climbing','clb', 'Sport climbing is a modern sport that has become immensely popular over the past 20 years. It is a young, mixed-gender sport – with 39 per cent of climbers under 18 years old – practised both outdoors and in a more urban format indoors. There are over 25 million climbers in 150 countries all over the world. In 1985, a group of climbers gathered in Bardonecchia, near Turin, Italy, for an event called “SportRoccia”, which became the first organised lead competition in which competitors climb within a certain time limit. One year later, the first competition event on an artificial climbing wall was organised in Vaulx-en-Velin near Lyon, France.');
insert into Sport (id, name, imageName, description) values (35,'Surfing','srf', 'Surfing is a water sport where an athlete performs manoeuvres on a wave while standing on a board. Surfing is believed to have been practised by fishermen in ancient times in Peru and later, in around 400 AD, across Polynesia. James King, who served under explorer Captain James Cook, wrote about surfing in Hawaii after Cook died in 1779. Prehistoric man learned to swim in order to cross rivers and lakes - we know this because cave paintings from the Stone Age depicting swimmers have been found in Egypt. Swimming was also referred to in Greek mythology.');
insert into Sport (id, name, imageName, description) values (36,'Swimming','swm', 'The act of swimming dates to prehistoric times, but it wasn’t until the 19th century that it became widely practiced as a competitive sport. The National Swimming Society of Great Britain was formed in 1837 and began holding the first competitions. At the time, most swimmers used the breaststroke, or a form of it. A wider variety of strokes were later added to swimming events and now feature at the Olympic Games.');
insert into Sport (id, name, imageName, description) values (37,'Table Tennis','tte', 'Table tennis is derived from lawn tennis and was initially played as after-dinner entertainment among upper-class English families who would use whatever they could find as equipment. At the time, they would place books on a table to serve as a net, the lids of cigar boxes for rackets and a rounded-off cork from a champagne bottle as the ball. Thankfully, table tennis equipment has evolved over time and in 1926 competitions were organised in Berlin and London, giving rise to the first world championships which were held in London that same year. Enormously popular in Asia, table tennis is played by over 40 million people around the globe, making it one of the most popular sports in the world.');
insert into Sport (id, name, imageName, description) values (38,'Taekwondo','tkw', 'Taekwondo, which translates to “the art of kicking and punching”, is a martial art with roots dating back to the Three Kingdoms Period of Ancient Korea (c. 57 BC to 668 AD) when Silla Dynasty warriors began to develop a martial art known as taekkyon ("foot-hand"). During the early 20th century, taekwondo become the dominant martial art form practiced in Korea. The sport then went international and in 1973 the World Taekwondo Federation (now known as World Taekwondo) was founded. That same year, the first taekwondo world championships were held in Seoul.');
insert into Sport (id, name, imageName, description) VALUES (39,'Tennis','ten', 'The precursor to tennis was the “jeu de paume,” or “game of the hand,” which originated in France in the 11th century. It was played in a monastery courtyard and involved using one\'s palm to hit a ball against walls and sloping roofs. Tennis, as we know it today, was developed in 19th-century England. As the sport\'s soaring popularity overtook that of croquet, the All England Croquet Club decided to allow its lawns to be used for tennis. Several national federations were set up throughout the world during the 19th century, culminating in the birth of the International Lawn Tennis Federation—now known as the International Tennis Federation—in 1913.');
insert into Sport (id, name, imageName, description) values (40,'Trampoline','gtr', 'Trampolining was invented in 1934 by American gymnast George Nissen who, after watching trapeze acrobats perform tricks while bouncing off safety nets, built the first prototype trampoline to recreate their acrobatics. Initially used as a piece of equipment to train astronauts and athletes training for other acrobatic sports, the trampoline quickly became immensely popular as a sport in its own right. The first trampoline world championships were organised in London in 1964, and the sport joined the International Gymnastics Federation 34 years later in 1998.');
insert into Sport (id, name, imageName, description) values (41,'Triathlon','tri', 'Although it comprises three long-established disciplines, triathlon is still a young sport, having only been invented the 1970s by the San Diego Track Club as alternative workout to traditional track training. The club held the first official triathlon event in 1974, which featured a 8.5km run, an 8km cycle and a swim just short of 550m. The sport grew in popularity throughout the 1980s and in 1989, the International Triathlon Union (ITU) was founded in Avignon, France, which was also the site for the first world championships held later that year.');
insert into Sport (id, name, imageName, description) values (42,'Volleyball','vvo', 'William G. Morgan, a YMCA physical education director and a student at Springfield College, is credited with creating the game of volleyball in 1895 in Holyoke, Massachusetts. Mintonette (as volleyball was called at the time) was designed to be an indoor pastime that could be enjoyed by older members of the YMCA, and took some of its characteristics from other sports including tennis and handball. Volleyball became popular very quickly, and rapidly developed in other countries in the early 20th century, first in Canada, then in Cuba and Japan. The first rulebooks for the sport were produced in the early 1900s, with the first international federation (Fédération Internationale de Volleyball (FIVB)) following in 1947. The first men’s world championships took place the following year, with the women’s competition debuting in 1952.');
insert into Sport (id, name, imageName, description) values (43,'Waterpolo','wpo', 'Water polo was initially a dangerous sport that first developed in the rivers and lakes of mid-19th century England as an aquatic version of rugby. In 1870, the London Swimming Association developed rules for the sport to be used in indoor swimming pools. Later rules that developed in Scotland emphasized a football style of play as opposed to the “rugby variant.” Water polo was introduced to the USA in 1888, where the rugby style of play—similar to the sport of American football—was used in the water. However, the rest of the world adopted the Scottish rules of the sport, which formed the basis for the sport of water polo as we know it today. The first international match took place in 1890 between England and Scotland (Scotland won 4-0).');
insert into Sport (id, name, imageName, description) values (44,'Weightlifting','wlf', 'Weightlifting—often known as Olympic weightlifting—has been around for thousands of years, yet the objective remains the same: the athlete who lifts the most weight wins. Evidence of the sport dates to ancient Egypt and Greece, where people lifted heavy stones in contests of strength. Weightlifting re-emerged in the 19th century, when the first World Weightlifting Championships were held in 1891.');
insert into Sport (id, name, imageName, description) values (45,'Wrestlingg','wre', 'Wrestling is one of the oldest sports in human history—if not the oldest. Multiple sculptures, reliefs and cave drawings—some of which date to around 15,000 years ago—show wrestlers using various holds that are still used in the present-day sport. Wrestling was a key part of the ancient Olympic Games, where it was first contested in 708 BCE. Wrestling matches were organised as its own event in two disciplines (‘upright’ and ‘ground’ wrestling) and as part of the pentathlon. Modern wrestling consists of two separate disciplines: Greco-Roman wrestling, a wrestling style based on the ancient sport, and freestyle wrestling, a more modern format.');
