insert into Country values (1,'Afghanistan');
insert into Country values (2,'Albania');
insert into Country values (3,'Algeria');
insert into Country values (4,'Andorra');
insert into Country values (5,'Angola');
insert into Country values (6,'Antigua & Deps');
insert into Country values (7,'Argentina');
insert into Country values (8,'Armenia');
insert into Country values (9,'Australia');
insert into Country values (10,'Austria');
insert into Country values (11,'Azerbaijan');
insert into Country values (12,'Bahamas');
insert into Country values (13,'Bahrain');
insert into Country values (14,'Bangladesh');
insert into Country values (15,'Barbados');
insert into Country values (16,'Belarus');
insert into Country values (17,'Belgium');
insert into Country values (18,'Belize');
insert into Country values (19,'Benin');
insert into Country values (20,'Bhutan');
insert into Country values (21,'Bolivia');
insert into Country values (22,'Bosnia Herzegovina');
insert into Country values (23,'Botswana');
insert into Country values (24,'Brazil');
insert into Country values (25,'Brunei');
insert into Country values (26,'Bulgaria');
insert into Country values (27,'Burkina');
insert into Country values (28,'Burundi');
insert into Country values (29,'Cambodia');
insert into Country values (30,'Cameroon');
insert into Country values (31,'Canada');
insert into Country values (32,'Cape Verde');
insert into Country values (33,'Central African Rep');
insert into Country values (34,'Chad');
insert into Country values (35,'Chile');
insert into Country values (36,'China');
insert into Country values (37,'Colombia');
insert into Country values (38,'Comoros');
insert into Country values (39,'Congo');
insert into Country values (40,'Congo {Democratic Rep}');
insert into Country values (41,'Costa Rica');
insert into Country values (42,'Croatia');
insert into Country values (43,'Cuba');
insert into Country values (44,'Cyprus');
insert into Country values (45,'Czech Republic');
insert into Country values (46,'Denmark');
insert into Country values (47,'Djibouti');
insert into Country values (48,'Dominica');
insert into Country values (49,'Dominican Republic');
insert into Country values (50,'East Timor');
insert into Country values (51,'Ecuador');
insert into Country values (52,'Egypt');
insert into Country values (53,'El Salvador');
insert into Country values (54,'Equatorial Guinea');
insert into Country values (55,'Eritrea');
insert into Country values (56,'Estonia');
insert into Country values (57,'Ethiopia');
insert into Country values (58,'Fiji');
insert into Country values (59,'Finland');
insert into Country values (60,'France');
insert into Country values (61,'Gabon');
insert into Country values (62,'Gambia');
insert into Country values (63,'Georgia');
insert into Country values (64,'Germany');
insert into Country values (65,'Ghana');
insert into Country values (66,'Greece');
insert into Country values (67,'Grenada');
insert into Country values (68,'Guatemala');
insert into Country values (69,'Guinea');
insert into Country values (70,'Guinea-Bissau');
insert into Country values (71,'Guyana');
insert into Country values (72,'Haiti');
insert into Country values (73,'Honduras');
insert into Country values (74,'Hungary');
insert into Country values (75,'Iceland');
insert into Country values (76,'India');
insert into Country values (77,'Indonesia');
insert into Country values (78,'Iran');
insert into Country values (79,'Iraq');
insert into Country values (80,'Ireland {Republic}');
insert into Country values (81,'Israel');
insert into Country values (82,'Italy');
insert into Country values (83,'Ivory Coast');
insert into Country values (84,'Jamaica');
insert into Country values (85,'Japan');
insert into Country values (86,'Jordan');
insert into Country values (87,'Kazakhstan');
insert into Country values (88,'Kenya');
insert into Country values (89,'Kiribati');
insert into Country values (90,'Korea North');
insert into Country values (91,'Korea South');
insert into Country values (92,'Kosovo');
insert into Country values (93,'Kuwait');
insert into Country values (94,'Kyrgyzstan');
insert into Country values (95,'Laos');
insert into Country values (96,'Latvia');
insert into Country values (97,'Lebanon');
insert into Country values (98,'Lesotho');
insert into Country values (99,'Liberia');
insert into Country values (100,'Libya');
insert into Country values (101,'Liechtenstein');
insert into Country values (102,'Lithuania');
insert into Country values (103,'Luxembourg');
insert into Country values (104,'Macedonia');
insert into Country values (105,'Madagascar');
insert into Country values (106,'Malawi');
insert into Country values (107,'Malaysia');
insert into Country values (108,'Maldives');
insert into Country values (109,'Mali');
insert into Country values (110,'Malta');
insert into Country values (111,'Marshall Islands');
insert into Country values (112,'Mauritania');
insert into Country values (113,'Mauritius');
insert into Country values (114,'Mexico');
insert into Country values (115,'Micronesia');
insert into Country values (116,'Moldova');
insert into Country values (117,'Monaco');
insert into Country values (118,'Mongolia');
insert into Country values (119,'Montenegro');
insert into Country values (120,'Morocco');
insert into Country values (121,'Mozambique');
insert into Country values (122,'Myanmar, {Burma}');
insert into Country values (123,'Namibia');
insert into Country values (124,'Nauru');
insert into Country values (125,'Nepal');
insert into Country values (126,'Netherlands');
insert into Country values (127,'New Zealand');
insert into Country values (128,'Nicaragua');
insert into Country values (129,'Niger');
insert into Country values (130,'Nigeria');
insert into Country values (131,'Norway');
insert into Country values (132,'Oman');
insert into Country values (133,'Pakistan');
insert into Country values (134,'Palau');
insert into Country values (135,'Panama');
insert into Country values (136,'Papua New Guinea');
insert into Country values (137,'Paraguay');
insert into Country values (138,'Peru');
insert into Country values (139,'Philippines');
insert into Country values (140,'Poland');
insert into Country values (141,'Portugal');
insert into Country values (142,'Qatar');
insert into Country values (143,'Romania');
insert into Country values (144,'Russian Federation');
insert into Country values (145,'Rwanda');
insert into Country values (146,'St Kitts & Nevis');
insert into Country values (147,'St Lucia');
insert into Country values (148,'Saint Vincent & the Grenadines');
insert into Country values (149,'Samoa');
insert into Country values (150,'San Marino');
insert into Country values (151,'Sao Tome & Principe');
insert into Country values (152,'Saudi Arabia');
insert into Country values (153,'Senegal');
insert into Country values (154,'Serbia');
insert into Country values (155,'Seychelles');
insert into Country values (156,'Sierra Leone');
insert into Country values (157,'Singapore');
insert into Country values (158,'Slovakia');
insert into Country values (159,'Slovenia');
insert into Country values (160,'Solomon Islands');
insert into Country values (161,'Somalia');
insert into Country values (162,'South Africa');
insert into Country values (163,'South Sudan');
insert into Country values (164,'Spain');
insert into Country values (165,'Sri Lanka');
insert into Country values (166,'Sudan');
insert into Country values (167,'Suriname');
insert into Country values (168,'Swaziland');
insert into Country values (169,'Sweden');
insert into Country values (170,'Switzerland');
insert into Country values (171,'Syria');
insert into Country values (172,'Taiwan');
insert into Country values (173,'Tajikistan');
insert into Country values (174,'Tanzania');
insert into Country values (175,'Thailand');
insert into Country values (176,'Togo');
insert into Country values (177,'Tonga');
insert into Country values (178,'Trinidad & Tobago');
insert into Country values (179,'Tunisia');
insert into Country values (180,'Turkey');
insert into Country values (181,'Turkmenistan');
insert into Country values (182,'Tuvalu');
insert into Country values (183,'Uganda');
insert into Country values (184,'Ukraine');
insert into Country values (185,'United Arab Emirates');
insert into Country values (186,'United Kingdom');
insert into Country values (187,'United States');
insert into Country values (188,'Uruguay');
insert into Country values (189,'Uzbekistan');
insert into Country values (190,'Vanuatu');
insert into Country values (191,'Vatican City');
insert into Country values (192,'Venezuela');
insert into Country values (193,'Vietnam');
insert into Country values (194,'Yemen');
insert into Country values (195,'Zambia');
insert into Country values (196,'Zimbabwe');